# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-25 04:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards_won', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15000)])),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start', models.DateTimeField()),
                ('length', models.IntegerField(choices=[(1, '1h'), (2, '2h'), (3, '3h'), (4, '4h'), (8, '8h'), (24, '1d'), (48, '2d'), (72, '3d')])),
                ('size', models.IntegerField(choices=[(100, '100 players'), (150, '150 players'), (200, '200 players'), (250, '250 players'), (300, '300 players'), (500, '500 playesr'), (600, '600 players'), (800, '800 players'), (1000, '1000 players')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='tournaments.Series')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
