# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-09 05:56
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards_won', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15000)])),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='added',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='schedule',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='host',
        ),
        migrations.AddField(
            model_name='tournament',
            name='length',
            field=models.IntegerField(choices=[(1, '1h'), (2, '2h'), (3, '3h'), (4, '4h'), (8, '8h'), (24, '1d'), (48, '2d'), (72, '3d')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournament',
            name='size',
            field=models.IntegerField(choices=[(100, '100 players'), (150, '150 players'), (200, '200 players'), (250, '250 players'), (300, '300 players'), (500, '500 playesr'), (600, '600 players'), (800, '800 players'), (1000, '1000 players')]),
        ),
        migrations.AddField(
            model_name='result',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tournaments.Tournament'),
        ),
        migrations.AddField(
            model_name='result',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='tournaments.Series'),
            preserve_default=False,
        ),
    ]
