# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-01 23:25
from __future__ import unicode_literals

import adminsortable.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_auto_20160925_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshots')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='length',
        ),
        migrations.AlterField(
            model_name='result',
            name='user',
            field=models.ForeignKey(help_text='Only clan members are allowed to earn tournament points', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='size',
            field=models.IntegerField(choices=[(50, '50 players'), (100, '100 players'), (200, '200 players'), (1000, '1000 players')]),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='tournament',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament'),
        ),
    ]
