# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-22 01:50
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0002_auto_20160909_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 22, 1, 50, 36, 465385, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='participants',
            field=models.ManyToManyField(related_name='series', to=settings.AUTH_USER_MODEL),
        ),
    ]
