# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-01 23:54
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_auto_20161001_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='image',
            field=filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='filer.Image'),
        ),
    ]
