# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0003_auto_20160906_2348'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='decks',
            field=models.ManyToManyField(related_name='users', to='decks.Deck'),
        ),
    ]
