# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-09 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0004_auto_20160907_0032'),
        ('users', '0002_user_decks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_decks',
            field=models.ManyToManyField(related_name='fans', to='decks.Deck'),
        ),
    ]
