# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-10 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160909_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='decks',
        ),
        migrations.AlterField(
            model_name='user',
            name='voted_decks',
            field=models.ManyToManyField(related_name='voters', through='decks.Vote', to='decks.Deck'),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
