# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-10 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0005_inclusion_tag_vote'),
        ('users', '0005_auto_20160910_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='decks',
            field=models.ManyToManyField(related_name='users', through='decks.Inclusion', to='decks.Deck'),
        ),
    ]
