# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-21 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='value',
            field=models.CharField(max_length=200),
        ),
    ]
