# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-21 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160921_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='value',
            new_name='text',
        ),
    ]
