import requests

cards = ['knight.png',
'archers.png',
'speargoblins.png',
'arrows.png',
'goblins.png',
'bomber.png',
'fireball.png',
'giant.png',
'musketeer.png',
'prince.png',
'goblinhut.png',
'minipekka.png',
'valkyrie.png',
'witch.png',
'skeletonarmy.png',
'babydragon.png',
'lightning.png',
'goblinbarrel.png',
'balloon.png',
'xbow.png',
'tombstone.png',
'rocket.png',
'elixircollector.png',
'infernotower.png',
'mirror.png',
'wizard.png',
'barbarianhut.png',
'freeze.png',
'rage.png',
'giantskeleton.png',
'minionhorde.png',
'skeletons.png',
'hogrider.png',
'barbarians.png',
'minions.png',
'golem.png',
'bombtower.png',
'pekka.png',
'zap.png',
'cannon.png',
'tesla.png',
'mortar.png',
'poison.png',
'darkprince.png',
'icewizard.png',
'royalgiant.png',
'princess.png',
'threemusketeers.png',
'guards.png',
'firespirits.png',
'furnace.png',
'sparky.png',
'lavahound.png',
'miner.png',
'icespirit.png',
'bowler.png',
'lumberjack.png',
'thelog.png',
]

for x in cards:
    str1 = '%s' % (cards[x-1])
    str2 = 'http://clashroyaledeckbuilder.com/assets/cards/%s.png' % (x)

    f = open(str1, 'wb')
    f.write(requests.get(str2).content)
    f.close()
