# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 19:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularity', models.IntegerField()),
                ('cost_average', models.IntegerField()),
                ('cards', models.ManyToManyField(to='cards.Card')),
                ('current_favorite_of', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clans',
                'verbose_name': 'Clan',
            },
        ),
    ]
