# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_auto_20160823_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deck',
            options={'verbose_name': 'deck', 'verbose_name_plural': 'decks'},
        ),
        migrations.RemoveField(
            model_name='deck',
            name='archetype',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='cost_average',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='current_favorite_of',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='popularity',
        ),
        migrations.AlterField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(related_name='decks', to='cards.Card'),
        ),
    ]
