# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-07 00:32
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('decks', '0003_auto_20160906_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 7, 0, 32, 36, 795982, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deck',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_decks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
