# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-10 23:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('decks', '0004_auto_20160907_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='decks.Deck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('inclusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='decks.Inclusion')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, 'Up'), (-1, 'Down')])),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='decks.Deck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
