# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-11 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0005_inclusion_tag_vote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inclusion',
            unique_together=set([('user', 'deck')]),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('user', 'deck')]),
        ),
    ]
