# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20160809_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('name',), 'verbose_name': 'card', 'verbose_name_plural': 'cards'},
        ),
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, upload_to='cards'),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
