# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='image',
        ),
    ]
