# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-01 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_remove_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(default='none.jpg', upload_to='cards'),
            preserve_default=False,
        ),
    ]
